site_name: Kungfu pandas Docs
extra_css: [style.css]
repo_url: https://github.com/david26694/kungfu_pandas
site_url: https://david26694.github.io/kungfu_pandas/
site_description: Functions that work well with pandas.
site_author: David Masip
use_directory_urls: false
nav:
  - Home:
    - Index: index.md
  - API:
      - Kungfu pandas: api/kungfu_pandas.md
plugins:
  - mkdocstrings:
      watch:
        - kungfu_pandas
  - search
copyright: Copyright &copy; 2021 Maintained by David Masip.
theme:
  name: material
  font:
    text: Ubuntu
    code: Ubuntu Mono
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: blue
markdown_extensions:
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.highlight:
      use_pygments: true
  - toc:
      permalink: true
